### ISSUE TITLE
Extra method to be deleted and another to be edited

### ISSUE THREAD

**Issue by AhmedBatwa** [AhmedBatwa/Shipping-Company-Project#5]
In class ShippingCompany, the method "receive" can just be merged the loop of method "generateShipments", and we can change the name of "gnerateShipments" into "receiveShipments" to make it clearer.

**Comment by Mhd-Ghd** [comment]
although it is a good idea to do that, BUT **_gnerateShipments_** is meant to generate a random case of shipment, receiver and sender. And pass that whole case to the company to **_receive_** it this is a real-world example of receiving a shipment.

thanks again for the suggestion.
